<?php
namespace test\config;

require_once dirname( __FILE__ ) . '/../../../config/switcher.class.php';

/**
 * Test class for switcher.
 * Generated by PHPUnit on 2011-09-07 at 13:43:57.
 */
class switcher extends \PHPUnit_Framework_TestCase {

	/**
	 * @covers	\config\switcher::is_on
	 * @covers	\config\switcher::is_off
	 * @covers	\config\switcher::on
	 * @covers	\config\switcher::off
	 */
	public function test_is_on_or_off() {
		$this->assertTrue( \config\switcher::is_on( \config\switcher::DEFAULT_ON ) );
		$this->assertFalse( \config\switcher::is_off( \config\switcher::DEFAULT_ON ) );

		$this->assertFalse( \config\switcher::is_on( \config\switcher::SUPPOSE_ON ) );
		$this->assertTrue( \config\switcher::is_off( \config\switcher::SUPPOSE_ON ) );

		\config\switcher::on( \config\switcher::SUPPOSE_ON );

		$this->assertTrue( \config\switcher::is_on( \config\switcher::SUPPOSE_ON ) );
		$this->assertFalse( \config\switcher::is_off( \config\switcher::SUPPOSE_ON ) );

		\config\switcher::off( \config\switcher::DEFAULT_ON );

		$this->assertFalse( \config\switcher::is_on( \config\switcher::DEFAULT_ON ) );
		$this->assertTrue( \config\switcher::is_off( \config\switcher::DEFAULT_ON ) );

		$this->assertFalse( \config\switcher::is_on( \config\switcher::SUPPOSE_ON ) );
		$this->assertTrue( \config\switcher::is_off( \config\switcher::SUPPOSE_ON ) );

		\config\switcher::off( \config\switcher::SUPPOSE_ON );

		$this->assertFalse( \config\switcher::is_on( \config\switcher::SUPPOSE_ON ) );
		$this->assertTrue( \config\switcher::is_off( \config\switcher::SUPPOSE_ON ) );
	}

}
